### PR TITLE
add linebreak for snippets

### PR DESCRIPTION
**Pull request by arcturus140**
i added a linebreak for some snippets

### CODE REVIEW

**Comment by rwols** [comment]
Overall not a bad idea. But don't you think this would be confusing when using the "snippets" in CMake.sublime-completions? If you want to modify those, run/update the script in tools/update-commands.py with

```
python3 tools/update-commands.py
```

**Comment by rwols** [comment]
Hmm, now that I think about it, those snippets in CMake.sublime-completions put the caret in-between the parentheses, so it wouldn't make sense to add a newline for those.

**Comment by arcturus140** [comment]
you end up on the new line with a final tab. It is the same as using $0

**Comment by arcturus140** [comment]
a Linebreak might be annoying in some cases so I didn't add it in the script. But consistency is going to be an issue now that I think of it.

**Comment by arcturus140** [comment]
i am not sure i understand. The snippets are not path of `CMake.sublime-completions`. When running `tools/parse-snippets.py` the snippet is found and skipped as special command. 

using `tools/update-commands.py`, `SublimeCommands.sublime-syntax` is not affected by this change and remains unchanged.

**Comment by arcturus140** [comment]
https://github.com/zyxar/Sublime-CMakeLists/pull/51/commits/86da06ed9d4f0e70e305aabf26ca97078e9c8431 adds a linebreak to every command. This is only for discussion. I don't like this change because now i can no longer cycle through multiple commands. 

E.g., on master you can type `install` and tab through several options like `install_files`, `install_programs`, etc. With the new line added in https://github.com/zyxar/Sublime-CMakeLists/pull/51/commits/86da06ed9d4f0e70e305aabf26ca97078e9c8431 this isn't possible.

**Comment by rwols** [comment]
Please merge with the master branch.

**Pull request closed without merging**
