### PR TITLE
add new snippet for generator expressions

### LINKED ISSUE #65: new snippet for generator expressions
type gen + tab to create a new generator expression

WIP:

```xml
<snippet>
	<content><![CDATA[
\$<${1:op}${2::${3:exp}}>$0
]]></content>
	<tabTrigger>gen</tabTrigger>
	<scope>source.cmake,source.cmakeeditor</scope>
	<description>generator expression</description>
</snippet>
```

I'll make a PR for this soon, created this issue to discuss the behaviour.

### PR DESCRIPTION
**Pull request by arcturus140**
this PR closes #65

### CODE REVIEW

**Review by rwols — APPROVED** [review]

**Comment by rwols** [comment]
Thanks :)

**Comment by rwols** [comment]
Do you have plans for more snippet adjustments?

**Comment by arcturus140** [comment]
Not for now. I am open to ideas, though. 

Auto completion for generator expressions could be added. There had been quite a few changes since CMake 3.0. Do you wish to keep this plug-in based on CMake 3.0 or are you willing to accept changes for more recent versions?

One thing i find annoying is the repeated arguments in the `endif`, `else`, `endforeach` clauses. It is no longer required since 2.8 and discouraged in modern CMake.

**Comment by rwols** [comment]
I would welcome more modern idioms!

**Pull request merged**
