### PR TITLE
Fix47.1

### LINKED ISSUE #47: Bring back fancy snippets
I have not been able to get snippets and auto completion to work after #44. Please update the README with instruction on how to setup the plugin.

### PR DESCRIPTION
**Pull request by arcturus140**
this PR closes #47. It makes snippet scope more restrictive: build in commands are no longer suggested inside CMake variables.
it adds additional snippets for CMake variables

### CODE REVIEW

**Comment by arcturus140** [comment]
there are edge cases. For example variable completions are not triggered for arguments:

```cmake
foreach(var IN LISTS CMAKE_MODULE_PATH) ...
variable_watch(CMAKE_PROJECT) ...
unset(CMAKE_CURRENT_LIST_DIR) ...
```

need for this should be very rare

**Review by rwols — CHANGES_REQUESTED** [review]
Did you forget to commit the CMakeVariables.sublime-completions file? I don't see it

**Comment by arcturus140** [comment]
I didn't commit it because it is a generated file. Wouldn't it cause many merge conflicts in future development?

**Comment by rwols** [comment]
> Wouldn't it cause many merge conflicts in future development?

I don't see that happening.

**Comment by arcturus140** [comment]
@rwols done

**Review by rwols — APPROVED** [review]

**Comment by rwols** [comment]
Alright, let's roll with this :)

**Comment by rwols** [comment]
Two things:

1. There's a typo: `buildin variable` -> `builtin variable`
2. It's a bit odd that the triggers are lowercase, while the replacements are uppercase. Why not keep the trigger uppercased as well?

**Comment by arcturus140** [comment]
1. :smile: i'll fix it
2. i don't like to type all caps, it's annoying. It is also common to have all triggers lowercase though i don't know *how* common. It is also the main reason why i use autocompletion, because my variable names are uppercase. It is very common for CMake although i am not sure it is an official convention

**Comment by arcturus140** [comment]
there is a need for variable completion outside of variable scopes, too. For example:

`if(NOT CMAKE_BUILD_TYPE)`

but i don't want to make it too fancy. Text completion quickly becomes too intrusive, also lets not forget about text buffer that triggers in this case.

**Comment by arcturus140** [comment]
@rwols i just tested it and it seems triggers are case insensitive?

**Comment by rwols** [comment]
> It is also common to have all triggers lowercase though i don't know how common.

Is it?

It's just unexpected that if I'm reading `build_shared_libs` in my auto-complete widget, that it completes to `BUILD_SHARED_LIBS`. But let's make separate issues for this.

**Comment by arcturus140** [comment]
i wouldn't know a good place to look for to be sure. I asked in Sublime forum but didn't receive much input due to the time of the year.

**Pull request merged**
