### PR TITLE
Rewrite for sublime-syntax file

### PR DESCRIPTION
**Pull request by rwols**
This is a work-in-progress branch where I rewrite the syntax from scratch in a sublime-syntax file. Feel free to add comments.

### CODE REVIEW

**Comment by rwols** [comment]
schermafbeelding 2017-04-06 om 20 25 42

OK, it's starting to look pretty good. I still need to implement [bracket arguments](https://cmake.org/cmake/help/v3.0/manual/cmake-language.7.html#bracket-argument) and [bracket comments](https://cmake.org/cmake/help/v3.0/manual/cmake-language.7.html#bracket-comment).

**Comment by rwols** [comment]
OK well it's pretty much done I think. Can you review the changes?

**Comment by zyxar** [comment]
@rwols I'll do it when there's enough timespan. Thanks!

**Comment by rwols** [comment]
These last two commits add symbol indexing for variables that you set with the `set(...)` command

schermafbeelding 2017-04-10 om 12 33 32

**Pull request merged**
